// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <math.h>   // isnan
// system
#include <time.h>
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <sys/wait.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
// C++
#include <string>
#include <vector>
#include <unordered_map>
#include <algorithm>
// proj
#include "common.h"
#include "hashtable.h"
#include "zset.h"
#include "list.h"
#include "heap.h"
#include "thread_pool.h"
#include "list_type.h"
#include "hash_type.h"


static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

static uint64_t get_monotonic_msec() {
    struct timespec tv = {0, 0};
    clock_gettime(CLOCK_MONOTONIC, &tv);
    return uint64_t(tv.tv_sec) * 1000 + tv.tv_nsec / 1000 / 1000;
}

static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

const size_t k_max_msg = 32 << 20;  // likely larger than the kernel buffer

typedef std::vector<uint8_t> Buffer;

// append to the back
static void buf_append(Buffer &buf, const uint8_t *data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}
// remove from the front
static void buf_consume(Buffer &buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming;    // data to be parsed by the application
    Buffer outgoing;    // responses generated by the application
    // timer
    uint64_t last_active_ms = 0;
    DList idle_node;
    // pub/sub
    bool subscribed = false;
    std::vector<std::string> channels;
};

// global states
static struct {
    HMap db;
    // a map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;
    // timers for idle connections
    DList idle_list;
    // timers for TTLs
    std::vector<HeapItem> heap;
    // the thread pool
    ThreadPool thread_pool;
    // pub/sub: channel -> subscribers
    std::unordered_map<std::string, std::vector<Conn *>> subs;
} g_data;

// application callback when the listening socket is ready
static int32_t handle_accept(int fd) {
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0) {
        msg_errno("accept() error");
        return -1;
    }
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
        ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
        ntohs(client_addr.sin_port)
    );

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a `struct Conn`
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    conn->last_active_ms = get_monotonic_msec();
    dlist_insert_before(&g_data.idle_list, &conn->idle_node);

    // put it into the map
    if (g_data.fd2conn.size() <= (size_t)conn->fd) {
        g_data.fd2conn.resize(conn->fd + 1);
    }
    assert(!g_data.fd2conn[conn->fd]);
    g_data.fd2conn[conn->fd] = conn;
    return 0;
}

static void pubsub_forget(Conn *conn);

static void conn_destroy(Conn *conn) {
    pubsub_forget(conn);
    (void)close(conn->fd);
    g_data.fd2conn[conn->fd] = NULL;
    dlist_detach(&conn->idle_node);
    delete conn;
}

const size_t k_max_args = 200 * 1000;

static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out) {
    if ((size_t)(end - cur) < 4) {
        return false;
    }
    memcpy(&out, cur, 4);
    cur += 4;
    return true;
}

static bool
read_str(const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out) {
    // `cur + n` could overflow the pointer when n comes off the wire
    if ((size_t)(end - cur) < n) {
        return false;
    }
    out.assign(cur, cur + n);
    cur += n;
    return true;
}

// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+

static int32_t
parse_req(const uint8_t *data, size_t size, std::vector<std::string> &out) {
    const uint8_t *end = data + size;
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr)) {
        return -1;
    }
    if (nstr > k_max_args) {
        return -1;  // safety limit
    }

    while (out.size() < nstr) {
        uint32_t len = 0;
        if (!read_u32(data, end, len)) {
            return -1;
        }
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back())) {
            return -1;
        }
    }
    if (data != end) {
        return -1;  // trailing garbage
    }
    return 0;
}

// error code for TAG_ERR
enum {
    ERR_UNKNOWN = 1,    // unknown command
    ERR_TOO_BIG = 2,    // response too big
    ERR_BAD_TYP = 3,    // unexpected value type
    ERR_BAD_ARG = 4,    // bad arguments
};

// data types of serialized data
enum {
    TAG_NIL = 0,    // nil
    TAG_ERR = 1,    // error code + msg
    TAG_STR = 2,    // string
    TAG_INT = 3,    // int64
    TAG_DBL = 4,    // double
    TAG_ARR = 5,    // array
};

// help functions for the serialization
static void buf_append_u8(Buffer &buf, uint8_t data) {
    buf.push_back(data);
}
static void buf_append_u32(Buffer &buf, uint32_t data) {
    buf_append(buf, (const uint8_t *)&data, 4);
}
static void buf_append_i64(Buffer &buf, int64_t data) {
    buf_append(buf, (const uint8_t *)&data, 8);
}
static void buf_append_dbl(Buffer &buf, double data) {
    buf_append(buf, (const uint8_t *)&data, 8);
}

// append serialized data types to the back
static void out_nil(Buffer &out) {
    buf_append_u8(out, TAG_NIL);
}
static void out_str(Buffer &out, const char *s, size_t size) {
    buf_append_u8(out, TAG_STR);
    buf_append_u32(out, (uint32_t)size);
    buf_append(out, (const uint8_t *)s, size);
}
static void out_int(Buffer &out, int64_t val) {
    buf_append_u8(out, TAG_INT);
    buf_append_i64(out, val);
}
static void out_dbl(Buffer &out, double val) {
    buf_append_u8(out, TAG_DBL);
    buf_append_dbl(out, val);
}
static void out_err(Buffer &out, uint32_t code, const std::string &msg) {
    buf_append_u8(out, TAG_ERR);
    buf_append_u32(out, code);
    buf_append_u32(out, (uint32_t)msg.size());
    buf_append(out, (const uint8_t *)msg.data(), msg.size());
}
static void out_arr(Buffer &out, uint32_t n) {
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, n);
}
static size_t out_begin_arr(Buffer &out) {
    out.push_back(TAG_ARR);
    buf_append_u32(out, 0);     // filled by out_end_arr()
    return out.size() - 4;      // the `ctx` arg
}
static void out_end_arr(Buffer &out, size_t ctx, uint32_t n) {
    assert(out[ctx - 1] == TAG_ARR);
    memcpy(&out[ctx], &n, 4);
}

// value types
enum {
    T_INIT  = 0,
    T_STR   = 1,    // string
    T_ZSET  = 2,    // sorted set
    T_LIST  = 3,    // linked list
    T_HASH  = 4,    // hash map
};

// KV pair for the top-level hashtable
struct Entry {
    struct HNode node;      // hashtable node
    std::string key;
    // for TTL
    size_t heap_idx = -1;   // array index to the heap item
    // value
    uint32_t type = 0;
    // one of the following
    std::string str;
    ZSet zset;
    LList list;
    HMap hash_map;
};

static Entry *entry_new(uint32_t type) {
    Entry *ent = new Entry();
    ent->type = type;
    return ent;
}

static void entry_set_ttl(Entry *ent, int64_t ttl_ms);

// a hash value owns its fields, but hm_clear() only frees the slot arrays
static void hash_clear(HMap *hmap) {
    std::vector<HEntry *> fields;
    hm_foreach(hmap, [](HNode *node, void *arg) -> bool {
        ((std::vector<HEntry *> *)arg)->push_back(container_of(node, HEntry, node));
        return true;
    }, &fields);
    hm_clear(hmap);
    for (HEntry *he : fields) {
        delete he;
    }
}

static void entry_del_sync(Entry *ent) {
    if (ent->type == T_ZSET) {
        zset_clear(&ent->zset);
    } else if (ent->type == T_LIST) {
        llist_clear(&ent->list);
    } else if (ent->type == T_HASH) {
        hash_clear(&ent->hash_map);
    }
    delete ent;
}

static void entry_del_func(void *arg) {
    entry_del_sync((Entry *)arg);
}

static void entry_del(Entry *ent) {
    // unlink it from any data structures
    entry_set_ttl(ent, -1); // remove from the heap data structure
    // run the destructor in a thread pool for large data structures
    size_t container_size = 0;
    if (ent->type == T_ZSET) {
        container_size = hm_size(&ent->zset.hmap);
    } else if (ent->type == T_LIST) {
        container_size = ent->list.len;
    } else if (ent->type == T_HASH) {
        container_size = hm_size(&ent->hash_map);
    }
    const size_t k_large_container_size = 1000;
    if (container_size > k_large_container_size) {
        thread_pool_queue(&g_data.thread_pool, &entry_del_func, ent);
    } else {
        entry_del_sync(ent);    // small; avoid context switches
    }
}

struct LookupKey {
    struct HNode node;  // hashtable node
    std::string key;
};

// equality comparison for the top-level hashstable
static bool entry_eq(HNode *node, HNode *key) {
    struct Entry *ent = container_of(node, struct Entry, node);
    struct LookupKey *keydata = container_of(key, struct LookupKey, node);
    return ent->key == keydata->key;
}

static bool hnode_same(HNode *node, HNode *key) {
    return node == key;
}

static bool entry_expired(Entry *ent, uint64_t now_ms) {
    return ent->heap_idx != (size_t)-1 && g_data.heap[ent->heap_idx].val <= now_ms;
}

// unlink a key from the keyspace and destroy it
static void entry_remove(Entry *ent) {
    HNode *node = hm_delete(&g_data.db, &ent->node, &hnode_same);
    assert(node == &ent->node);
    (void)node;
    entry_del(ent);
}

static void lookup_key_init(LookupKey &key, const std::string &name) {
    key.key = name;
    key.node.hcode = str_hash((const uint8_t *)key.key.data(), key.key.size());
}

// Every read goes through here. A key whose deadline has passed is removed
// on access, so it is never observable even before the timer sweep reaches it.
static Entry *entry_lookup(const std::string &name) {
    LookupKey key;
    lookup_key_init(key, name);
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node) {
        return NULL;
    }
    Entry *ent = container_of(node, Entry, node);
    if (entry_expired(ent, get_monotonic_msec())) {
        entry_remove(ent);
        return NULL;
    }
    return ent;
}

// look up a key for a write, creating it with `type` if absent;
// returns NULL if the key exists with another type
static Entry *entry_upsert(const std::string &name, uint32_t type) {
    Entry *ent = entry_lookup(name);
    if (ent) {
        return ent->type == type ? ent : NULL;
    }
    ent = entry_new(type);
    ent->key = name;
    ent->node.hcode = str_hash((const uint8_t *)name.data(), name.size());
    hm_insert(&g_data.db, &ent->node);
    return ent;
}

static const char *type_name(uint32_t type) {
    switch (type) {
        case T_STR:  return "string";
        case T_ZSET: return "zset";
        case T_LIST: return "list";
        case T_HASH: return "hash";
        default:     return "unknown";
    }
}

static void do_get(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) {
        return out_nil(out);
    }
    if (ent->type != T_STR) {
        return out_err(out, ERR_BAD_TYP, "not a string value");
    }
    return out_str(out, ent->str.data(), ent->str.size());
}

static void do_set(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_upsert(cmd[1], T_STR);
    if (!ent) {
        return out_err(out, ERR_BAD_TYP, "a non-string value exists");
    }
    ent->str.swap(cmd[2]);
    return out_nil(out);
}

static void do_del(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (ent) {
        entry_remove(ent);
    }
    return out_int(out, ent ? 1 : 0);
}

static void heap_delete(std::vector<HeapItem> &a, size_t pos) {
    // swap the erased item with the last item
    a[pos] = a.back();
    a.pop_back();
    // update the swapped item
    if (pos < a.size()) {
        heap_update(a.data(), pos, a.size());
    }
}

static void heap_upsert(std::vector<HeapItem> &a, size_t pos, HeapItem t) {
    if (pos < a.size()) {
        a[pos] = t;         // update an existing item
    } else {
        pos = a.size();
        a.push_back(t);     // or add a new item
    }
    heap_update(a.data(), pos, a.size());
}

// set the absolute monotonic deadline, or remove the TTL with (uint64_t)-1
static void entry_set_deadline(Entry *ent, uint64_t expire_at) {
    if (expire_at == (uint64_t)-1) {
        if (ent->heap_idx != (size_t)-1) {
            heap_delete(g_data.heap, ent->heap_idx);
            ent->heap_idx = -1;
        }
        return;
    }
    HeapItem item = {expire_at, &ent->heap_idx};
    heap_upsert(g_data.heap, ent->heap_idx, item);
}

// set or remove the TTL
static void entry_set_ttl(Entry *ent, int64_t ttl_ms) {
    if (ttl_ms < 0) {
        return entry_set_deadline(ent, (uint64_t)-1);
    }
    uint64_t now = get_monotonic_msec();
    // saturate instead of wrapping, which would expire the key at once
    uint64_t expire_at = (uint64_t)ttl_ms > UINT64_MAX - 1 - now
        ? UINT64_MAX - 1 : now + (uint64_t)ttl_ms;
    entry_set_deadline(ent, expire_at);
}

static int64_t entry_ttl_ms(Entry *ent) {
    if (ent->heap_idx == (size_t)-1) {
        return -1;
    }
    uint64_t expire_at = g_data.heap[ent->heap_idx].val;
    uint64_t now_ms = get_monotonic_msec();
    return expire_at > now_ms ? (int64_t)(expire_at - now_ms) : 0;
}

static bool str2int(const std::string &s, int64_t &out) {
    char *endp = NULL;
    out = strtoll(s.c_str(), &endp, 10);
    return !s.empty() && endp == s.c_str() + s.size();
}

// PEXPIRE key ttl_ms
static void do_expire(std::vector<std::string> &cmd, Buffer &out) {
    int64_t ttl_ms = 0;
    if (!str2int(cmd[2], ttl_ms)) {
        return out_err(out, ERR_BAD_ARG, "expect int64");
    }
    Entry *ent = entry_lookup(cmd[1]);
    if (ent) {
        entry_set_ttl(ent, ttl_ms);
    }
    return out_int(out, ent ? 1: 0);
}

// PTTL key
static void do_ttl(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    return out_int(out, ent ? entry_ttl_ms(ent) : -2);
}

static void do_keys(std::vector<std::string> &, Buffer &out) {
    uint64_t now_ms = get_monotonic_msec();
    std::vector<Entry *> live;
    struct Ctx { uint64_t now_ms; std::vector<Entry *> *live; } ctx = {now_ms, &live};
    hm_foreach(&g_data.db, [](HNode *node, void *arg) -> bool {
        Ctx *c = (Ctx *)arg;
        Entry *ent = container_of(node, Entry, node);
        if (!entry_expired(ent, c->now_ms)) {
            c->live->push_back(ent);
        }
        return true;
    }, &ctx);
    out_arr(out, (uint32_t)live.size());
    for (Entry *ent : live) {
        out_str(out, ent->key.data(), ent->key.size());
    }
}

static bool str2dbl(const std::string &s, double &out) {
    char *endp = NULL;
    out = strtod(s.c_str(), &endp);
    return !s.empty() && endp == s.c_str() + s.size() && !isnan(out);
}

// zadd zset score name
static void do_zadd(std::vector<std::string> &cmd, Buffer &out) {
    double score = 0;
    if (!str2dbl(cmd[2], score)) {
        return out_err(out, ERR_BAD_ARG, "expect float");
    }
    Entry *ent = entry_upsert(cmd[1], T_ZSET);
    if (!ent) {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }
    const std::string &name = cmd[3];
    bool added = zset_insert(&ent->zset, name.data(), name.size(), score);
    return out_int(out, (int64_t)added);
}

// Resolves a key that must hold a zset. A missing key yields an empty set
// (`*zset` is NULL, returns true); a key of another type returns false.
static bool expect_zset(const std::string &name, ZSet **zset) {
    Entry *ent = entry_lookup(name);
    *zset = ent && ent->type == T_ZSET ? &ent->zset : NULL;
    return !ent || ent->type == T_ZSET;
}

// zrem zset name
static void do_zrem(std::vector<std::string> &cmd, Buffer &out) {
    ZSet *zset = NULL;
    if (!expect_zset(cmd[1], &zset)) {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }
    const std::string &name = cmd[2];
    ZNode *znode = zset ? zset_lookup(zset, name.data(), name.size()) : NULL;
    if (znode) {
        zset_delete(zset, znode);
    }
    return out_int(out, znode ? 1 : 0);
}

// zscore zset name
static void do_zscore(std::vector<std::string> &cmd, Buffer &out) {
    ZSet *zset = NULL;
    if (!expect_zset(cmd[1], &zset)) {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }
    const std::string &name = cmd[2];
    ZNode *znode = zset ? zset_lookup(zset, name.data(), name.size()) : NULL;
    return znode ? out_dbl(out, znode->score) : out_nil(out);
}

// zquery zset score name offset limit
static void do_zquery(std::vector<std::string> &cmd, Buffer &out) {
    // parse args
    double score = 0;
    if (!str2dbl(cmd[2], score)) {
        return out_err(out, ERR_BAD_ARG, "expect fp number");
    }
    const std::string &name = cmd[3];
    int64_t offset = 0, limit = 0;
    if (!str2int(cmd[4], offset) || !str2int(cmd[5], limit)) {
        return out_err(out, ERR_BAD_ARG, "expect int");
    }

    ZSet *zset = NULL;
    if (!expect_zset(cmd[1], &zset)) {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }
    if (!zset || limit <= 0) {
        return out_arr(out, 0);
    }

    // seek to the key
    ZNode *znode = zset_seekge(zset, score, name.data(), name.size());
    znode = znode_offset(znode, offset);

    // output: `limit` counts members, each written as a (name, score) pair
    size_t ctx = out_begin_arr(out);
    int64_t n = 0;
    while (znode && n < limit) {
        out_str(out, znode->name, znode->len);
        out_dbl(out, znode->score);
        znode = znode_offset(znode, +1);
        n++;
    }
    out_end_arr(out, ctx, (uint32_t)(n * 2));
}

// ---- list commands ----

// lpush key val [val ...]
static void do_lpush(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_upsert(cmd[1], T_LIST);
    if (!ent) {
        return out_err(out, ERR_BAD_TYP, "not a list");
    }
    for (size_t i = 2; i < cmd.size(); i++) {
        llist_push(&ent->list, cmd[i]);
    }
    out_int(out, (int64_t)ent->list.len);
}

// lpop key
static void do_lpop(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_nil(out);
    if (ent->type != T_LIST) return out_err(out, ERR_BAD_TYP, "not a list");

    std::string val;
    if (llist_pop(&ent->list, val)) {
        out_str(out, val.data(), val.size());
    } else {
        out_nil(out);
    }
}

// llen key
static void do_llen(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_int(out, 0);
    if (ent->type != T_LIST) return out_err(out, ERR_BAD_TYP, "not a list");
    out_int(out, (int64_t)ent->list.len);
}

// lrange key start stop
static void do_lrange(std::vector<std::string> &cmd, Buffer &out) {
    int64_t start = 0, stop = 0;
    if (!str2int(cmd[2], start) || !str2int(cmd[3], stop)) {
        return out_err(out, ERR_BAD_ARG, "expect int");
    }
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_arr(out, 0);
    if (ent->type != T_LIST) return out_err(out, ERR_BAD_TYP, "not a list");

    // convert negative indices, then clamp to the list
    int64_t len = (int64_t)ent->list.len;
    if (start < 0) start += len;
    if (stop < 0) stop += len;
    if (start < 0) start = 0;
    if (stop >= len) stop = len - 1;
    if (start > stop) return out_arr(out, 0);

    size_t n = (size_t)(stop - start + 1);
    out_arr(out, (uint32_t)n);
    LNode *cur = llist_index(&ent->list, start);
    for (size_t i = 0; cur && i < n; i++) {
        out_str(out, cur->val.data(), cur->val.size());
        cur = cur->next;
    }
}

// ---- hash commands ----

static void hlookup_init(HLookup &hkey, const std::string &field) {
    hkey.field = field;
    hkey.node.hcode = str_hash((const uint8_t *)hkey.field.data(), hkey.field.size());
}

// hset key field val
static void do_hset(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_upsert(cmd[1], T_HASH);
    if (!ent) return out_err(out, ERR_BAD_TYP, "not a hash");

    HLookup hkey;
    hlookup_init(hkey, cmd[2]);
    HNode *fnode = hm_lookup(&ent->hash_map, &hkey.node, &hentry_eq);
    if (fnode) {
        container_of(fnode, HEntry, node)->val.swap(cmd[3]);
        return out_int(out, 0);
    }
    HEntry *he = new HEntry();
    he->field.swap(hkey.field);
    he->val.swap(cmd[3]);
    he->node.hcode = hkey.node.hcode;
    hm_insert(&ent->hash_map, &he->node);
    out_int(out, 1);
}

// hget key field
static void do_hget(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_nil(out);
    if (ent->type != T_HASH) return out_err(out, ERR_BAD_TYP, "not a hash");

    HLookup hkey;
    hlookup_init(hkey, cmd[2]);
    HNode *fnode = hm_lookup(&ent->hash_map, &hkey.node, &hentry_eq);
    if (!fnode) return out_nil(out);
    HEntry *he = container_of(fnode, HEntry, node);
    out_str(out, he->val.data(), he->val.size());
}

// hdel key field
static void do_hdel(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_int(out, 0);
    if (ent->type != T_HASH) return out_err(out, ERR_BAD_TYP, "not a hash");

    HLookup hkey;
    hlookup_init(hkey, cmd[2]);
    HNode *fnode = hm_delete(&ent->hash_map, &hkey.node, &hentry_eq);
    if (!fnode) return out_int(out, 0);
    delete container_of(fnode, HEntry, node);
    out_int(out, 1);
}

// hgetall key
static void do_hgetall(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_arr(out, 0);
    if (ent->type != T_HASH) return out_err(out, ERR_BAD_TYP, "not a hash");

    out_arr(out, (uint32_t)(hm_size(&ent->hash_map) * 2));
    hm_foreach(&ent->hash_map, [](HNode *node, void *arg) -> bool {
        HEntry *he = container_of(node, HEntry, node);
        Buffer &obuf = *(Buffer *)arg;
        out_str(obuf, he->field.data(), he->field.size());
        out_str(obuf, he->val.data(), he->val.size());
        return true;
    }, &out);
}

// ---- bitmap commands ----

// Bit offsets are capped as in Redis (512 MB strings), so a client cannot
// make one setbit allocate an arbitrary amount of memory.
const int64_t k_max_bit_offset = ((int64_t)1 << 32) - 1;

// setbit key offset value
static void do_setbit(std::vector<std::string> &cmd, Buffer &out) {
    int64_t offset = 0, bit = 0;
    if (!str2int(cmd[2], offset) || !str2int(cmd[3], bit)
        || offset < 0 || offset > k_max_bit_offset || (bit != 0 && bit != 1)) {
        return out_err(out, ERR_BAD_ARG, "expect uint offset and 0/1");
    }
    Entry *ent = entry_upsert(cmd[1], T_STR);
    if (!ent) return out_err(out, ERR_BAD_TYP, "not a string");

    size_t byte_pos = (size_t)(offset / 8);
    int bit_off = (int)(offset % 8);
    if (byte_pos >= ent->str.size()) {
        ent->str.resize(byte_pos + 1, 0);
    }
    uint8_t old_bit = (ent->str[byte_pos] >> bit_off) & 1;
    if (bit) {
        ent->str[byte_pos] |= (uint8_t)(1 << bit_off);
    } else {
        ent->str[byte_pos] &= (uint8_t)~(1 << bit_off);
    }
    out_int(out, (int64_t)old_bit);
}

// getbit key offset
static void do_getbit(std::vector<std::string> &cmd, Buffer &out) {
    int64_t offset = 0;
    if (!str2int(cmd[2], offset) || offset < 0) {
        return out_err(out, ERR_BAD_ARG, "expect uint offset");
    }
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_int(out, 0);
    if (ent->type != T_STR) return out_err(out, ERR_BAD_TYP, "not a string");

    size_t byte_pos = (size_t)(offset / 8);
    int bit_off = (int)(offset % 8);
    if (byte_pos >= ent->str.size()) return out_int(out, 0);
    int64_t b = (ent->str[byte_pos] >> bit_off) & 1;
    out_int(out, b);
}

// bitcount key [start end]
static void do_bitcount(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_int(out, 0);
    if (ent->type != T_STR) return out_err(out, ERR_BAD_TYP, "not a string");

    size_t start = 0;
    size_t end = ent->str.size();
    if (cmd.size() >= 3) {
        int64_t s = 0;
        if (!str2int(cmd[2], s)) return out_err(out, ERR_BAD_ARG, "expect int");
        if (s < 0) s = (int64_t)ent->str.size() + s;
        if (s < 0) s = 0;
        start = (size_t)s;
    }
    if (cmd.size() >= 4) {
        int64_t e = 0;
        if (!str2int(cmd[3], e)) return out_err(out, ERR_BAD_ARG, "expect int");
        if (e < 0) e = (int64_t)ent->str.size() + e;
        if (e < 0) { out_int(out, 0); return; }
        end = (size_t)e + 1;
    }

    if (start > ent->str.size()) start = ent->str.size();
    if (end > ent->str.size()) end = ent->str.size();

    int64_t count = 0;
    for (size_t i = start; i < end; i++) {
        count += __builtin_popcount((uint8_t)ent->str[i]);
    }
    out_int(out, count);
}

// ---- misc commands ----

// EXISTS key
static void do_exists(std::vector<std::string> &cmd, Buffer &out) {
    out_int(out, entry_lookup(cmd[1]) ? 1 : 0);
}

// TYPE key
static void do_type(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    const char *tn = ent ? type_name(ent->type) : "none";
    out_str(out, tn, strlen(tn));
}

// STRLEN key
static void do_strlen(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_int(out, 0);
    if (ent->type != T_STR) return out_err(out, ERR_BAD_TYP, "not a string");
    out_int(out, (int64_t)ent->str.size());
}

// RENAME key newkey
static void do_rename(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_err(out, ERR_UNKNOWN, "no such key");
    if (cmd[1] == cmd[2]) return out_nil(out);

    Entry *existing = entry_lookup(cmd[2]);
    if (existing) entry_remove(existing);

    hm_delete(&g_data.db, &ent->node, &hnode_same);
    ent->key = cmd[2];
    ent->node.hcode = str_hash((const uint8_t *)ent->key.data(), ent->key.size());
    hm_insert(&g_data.db, &ent->node);
    out_nil(out);
}

// SCAN cursor [COUNT n]
static void do_scan(std::vector<std::string> &cmd, Buffer &out) {
    int64_t cursor = 0;
    if (!str2int(cmd[1], cursor) || cursor < 0) {
        return out_err(out, ERR_BAD_ARG, "expect uint cursor");
    }
    int64_t count = 10;
    for (size_t i = 2; i + 1 < cmd.size(); i++) {
        if (cmd[i] == "count" && str2int(cmd[i + 1], count)) break;
    }
    if (count < 1) count = 1;

    size_t total = hm_size(&g_data.db);
    size_t skip = (size_t)cursor;
    std::vector<std::string> keys;

    if (skip < total) {
        struct { size_t *skip; int64_t count; std::vector<std::string> *keys; } ctx;
        ctx.skip = &skip; ctx.count = count; ctx.keys = &keys;
        hm_foreach(&g_data.db, [](HNode *hnode, void *arg) -> bool {
            auto *c = (decltype(ctx) *)arg;
            if (*c->skip > 0) { (*c->skip)--; return true; }
            if ((int64_t)c->keys->size() >= c->count) return false;
            c->keys->push_back(container_of(hnode, Entry, node)->key);
            return true;
        }, &ctx);
    }

    int64_t next = (int64_t)keys.size() < count ? 0 : cursor + (int64_t)keys.size();
    out_arr(out, (uint32_t)(1 + keys.size()));
    out_int(out, next);
    for (size_t i = 0; i < keys.size(); i++) {
        out_str(out, keys[i].data(), keys[i].size());
    }
}

// DEBUG
static void do_debug(std::vector<std::string> &, Buffer &out) {
    int64_t nconn = 0;
    for (Conn *c : g_data.fd2conn) if (c) nconn++;
    out_arr(out, 4);
    out_str(out, "keys", 4);
    out_int(out, (int64_t)hm_size(&g_data.db));
    out_str(out, "connections", 11);
    out_int(out, nconn);
}

// OBJECT key
static void do_object(std::vector<std::string> &cmd, Buffer &out) {
    Entry *ent = entry_lookup(cmd[1]);
    if (!ent) return out_nil(out);

    const char *tn = type_name(ent->type);
    out_arr(out, 4);
    out_str(out, "type", 4);
    out_str(out, tn, strlen(tn));
    out_str(out, "ttl", 3);
    out_int(out, entry_ttl_ms(ent));
}
static void response_end(Buffer &out, size_t header);
static void response_begin(Buffer &out, size_t *header);
static void response_end(Buffer &out, size_t header);
static void do_request(std::vector<std::string> &cmd, Conn *conn, Buffer &out);

// A subscribed client's output is bounded: a subscriber that stops reading
// is disconnected instead of growing its buffer without limit.
const size_t k_max_pending_out = 2 * k_max_msg;

static void sub_remove(const std::string &channel, Conn *conn) {
    auto it = g_data.subs.find(channel);
    if (it == g_data.subs.end()) {
        return;
    }
    std::vector<Conn *> &vec = it->second;
    vec.erase(std::remove(vec.begin(), vec.end(), conn), vec.end());
    if (vec.empty()) {
        g_data.subs.erase(it);
    }
}

static void pubsub_forget(Conn *conn) {
    for (const std::string &ch : conn->channels) {
        sub_remove(ch, conn);
    }
    conn->channels.clear();
    conn->subscribed = false;
}

// Each subscribe/unsubscribe acknowledgement is its own frame, one per
// channel, as in Redis. Packing several values into one frame would break the
// one-value-per-frame rule the client relies on to match replies.
static void out_pubsub_frame(Buffer &out, const char *kind, const std::string *channel, int64_t n) {
    size_t header = 0;
    response_begin(out, &header);
    out_arr(out, 3);
    out_str(out, kind, strlen(kind));
    if (channel) {
        out_str(out, channel->data(), channel->size());
    } else {
        out_nil(out);
    }
    out_int(out, n);
    response_end(out, header);
}

// subscribe channel [channel ...]
static void do_subscribe(std::vector<std::string> &cmd, Conn *conn, Buffer &out) {
    for (size_t i = 1; i < cmd.size(); i++) {
        const std::string &channel = cmd[i];
        auto it = std::find(conn->channels.begin(), conn->channels.end(), channel);
        if (it == conn->channels.end()) {
            conn->channels.push_back(channel);
            g_data.subs[channel].push_back(conn);
        }
        out_pubsub_frame(out, "subscribe", &channel, (int64_t)conn->channels.size());
    }
    conn->subscribed = true;
}

// unsubscribe [channel ...]; no channels means all of them
static void do_unsubscribe(std::vector<std::string> &cmd, Conn *conn, Buffer &out) {
    std::vector<std::string> targets(cmd.begin() + 1, cmd.end());
    if (targets.empty()) {
        targets = conn->channels;
    }
    if (targets.empty()) {
        out_pubsub_frame(out, "unsubscribe", NULL, 0);
    }
    for (const std::string &channel : targets) {
        auto it = std::find(conn->channels.begin(), conn->channels.end(), channel);
        if (it != conn->channels.end()) {
            conn->channels.erase(it);
            sub_remove(channel, conn);
        }
        out_pubsub_frame(out, "unsubscribe", &channel, (int64_t)conn->channels.size());
    }
    if (conn->channels.empty()) {
        conn->subscribed = false;
    }
}

// publish channel message
static void do_publish(std::vector<std::string> &cmd, Conn *, Buffer &out) {
    const std::string &channel = cmd[1];
    const std::string &msg = cmd[2];

    auto it = g_data.subs.find(channel);
    int64_t count = 0;
    if (it != g_data.subs.end()) {
        // build the message notification frame
        Buffer notification;
        size_t header;
        response_begin(notification, &header);
        out_arr(notification, 3);
        out_str(notification, "message", 7);
        out_str(notification, channel.data(), channel.size());
        out_str(notification, msg.data(), msg.size());
        response_end(notification, header);

        std::vector<Conn *> too_slow;
        for (Conn *sub : it->second) {
            if (sub->outgoing.size() + notification.size() > k_max_pending_out) {
                too_slow.push_back(sub);
                continue;
            }
            buf_append(sub->outgoing, notification.data(), notification.size());
            sub->want_read = false;
            sub->want_write = true;
            count++;
        }
        // destroyed after the loop, because it edits the subscriber list
        for (Conn *sub : too_slow) {
            fprintf(stderr, "dropping slow subscriber: %d\n", sub->fd);
            conn_destroy(sub);
        }
    }

    out_int(out, count);
}

// ---- persistence ----
//
// prism.rdb is a snapshot of the whole keyspace. prism.aof logs every write
// made after that snapshot, so startup is "load the snapshot, replay the log".
// The log must never hold writes the snapshot already contains: replaying a
// non-idempotent command such as lpush twice would duplicate data.
//
// bgsave snapshots the state at fork time while the parent keeps writing, so
// at the fork the current log moves to prism.aof.pre (the writes the child's
// snapshot will contain) and a fresh log starts. prism.aof.pre is deleted only
// once the child has succeeded; until then startup replays it before the log.

static const char *k_rdb_path = "prism.rdb";
static const char *k_aof_path = "prism.aof";
static const char *k_aof_pre_path = "prism.aof.pre";

static FILE *aof_file = NULL;
static bool aof_dirty = false;          // written since the last fsync
static uint64_t aof_last_sync_ms = 0;
static pid_t bgsave_pid = -1;

static uint64_t get_wall_msec() {
    struct timespec tv = {0, 0};
    clock_gettime(CLOCK_REALTIME, &tv);
    return uint64_t(tv.tv_sec) * 1000 + tv.tv_nsec / 1000 / 1000;
}

static void aof_open() {
    aof_file = fopen(k_aof_path, "a");
    if (!aof_file) {
        fprintf(stderr, "warn: cannot open %s, persistence off\n", k_aof_path);
    }
}

static void aof_append(const uint8_t *data, size_t len) {
    if (!aof_file) return;
    fwrite(data, 1, len, aof_file);
    fflush(aof_file);
    aof_dirty = true;
}

// fflush() only hands data to the kernel; fsync once a second bounds what a
// power loss can take, without paying a disk flush per write
static void aof_sync() {
    uint64_t now_ms = get_monotonic_msec();
    if (aof_file && aof_dirty && now_ms - aof_last_sync_ms >= 1000) {
        fsync(fileno(aof_file));
        aof_dirty = false;
        aof_last_sync_ms = now_ms;
    }
}

static void aof_append_cmd(const std::vector<std::string> &args) {
    Buffer frame;
    buf_append_u32(frame, 0);
    buf_append_u32(frame, (uint32_t)args.size());
    for (const std::string &a : args) {
        buf_append_u32(frame, (uint32_t)a.size());
        buf_append(frame, (const uint8_t *)a.data(), a.size());
    }
    uint32_t len = (uint32_t)(frame.size() - 4);
    memcpy(&frame[0], &len, 4);
    aof_append(frame.data(), frame.size());
}

static bool is_write_cmd(const std::string &c) {
    return c == "set" || c == "del" || c == "pexpire" || c == "pexpireat"
        || c == "zadd" || c == "zrem" || c == "lpush" || c == "lpop"
        || c == "hset" || c == "hdel" || c == "setbit" || c == "rename";
}

// Logs a write. A relative TTL is logged as an absolute wall-clock deadline,
// because replaying "expire in 60 s" at startup would restart the countdown.
static void aof_log(const std::vector<std::string> &cmd, const uint8_t *frame, size_t len) {
    if (cmd[0] != "pexpire") {
        return aof_append(frame, len);
    }
    int64_t ttl_ms = 0;
    if (!str2int(cmd[2], ttl_ms)) return;
    std::string at = ttl_ms < 0 ? "-1" : std::to_string(get_wall_msec() + (uint64_t)ttl_ms);
    aof_append_cmd({"pexpireat", cmd[1], at});
}

// Converts a wall-clock deadline back to the monotonic clock the heap uses;
// a deadline already in the past maps to "now", so the key expires at once.
static uint64_t wall_to_monotonic(uint64_t wall_ms) {
    uint64_t now_wall = get_wall_msec();
    uint64_t now_mono = get_monotonic_msec();
    return wall_ms > now_wall ? now_mono + (wall_ms - now_wall) : now_mono;
}

// PEXPIREAT key unix_ms
static void do_expireat(std::vector<std::string> &cmd, Buffer &out) {
    int64_t at_ms = 0;
    if (!str2int(cmd[2], at_ms)) {
        return out_err(out, ERR_BAD_ARG, "expect int64");
    }
    Entry *ent = entry_lookup(cmd[1]);
    if (ent) {
        entry_set_deadline(ent, at_ms < 0 ? (uint64_t)-1 : wall_to_monotonic((uint64_t)at_ms));
    }
    return out_int(out, ent ? 1 : 0);
}

static void write_str(FILE *f, const char *data, size_t len) {
    uint32_t n = (uint32_t)len;
    fwrite(&n, 4, 1, f);
    fwrite(data, 1, len, f);
}

static bool cb_save(HNode *node, void *arg) {
    FILE *f = (FILE *)arg;
    Entry *ent = container_of(node, Entry, node);

    write_str(f, ent->key.data(), ent->key.size());
    uint8_t typ = (uint8_t)ent->type;
    fwrite(&typ, 1, 1, f);

    // stored as wall-clock time: the monotonic clock restarts at reboot
    int64_t ttl = entry_ttl_ms(ent);
    uint64_t expire = ttl < 0 ? 0 : get_wall_msec() + (uint64_t)ttl;
    fwrite(&expire, 8, 1, f);

    if (ent->type == T_STR) {
        write_str(f, ent->str.data(), ent->str.size());
    } else if (ent->type == T_ZSET) {
        uint32_t n = (uint32_t)hm_size(&ent->zset.hmap);
        fwrite(&n, 4, 1, f);
        hm_foreach(&ent->zset.hmap, [](HNode *znode, void *arg) -> bool {
            ZNode *z = container_of(znode, ZNode, hmap);
            FILE *fp = (FILE *)arg;
            fwrite(&z->score, 8, 1, fp);
            write_str(fp, z->name, z->len);
            return true;
        }, f);
    } else if (ent->type == T_LIST) {
        uint32_t n = (uint32_t)ent->list.len;
        fwrite(&n, 4, 1, f);
        // tail first: loading pushes each value onto the head
        for (LNode *cur = ent->list.tail; cur; cur = cur->prev) {
            write_str(f, cur->val.data(), cur->val.size());
        }
    } else if (ent->type == T_HASH) {
        uint32_t n = (uint32_t)hm_size(&ent->hash_map);
        fwrite(&n, 4, 1, f);
        hm_foreach(&ent->hash_map, [](HNode *hnode, void *arg) -> bool {
            HEntry *he = container_of(hnode, HEntry, node);
            FILE *fp = (FILE *)arg;
            write_str(fp, he->field.data(), he->field.size());
            write_str(fp, he->val.data(), he->val.size());
            return true;
        }, f);
    }
    return true;
}

// Writes to a temporary file and renames it over the snapshot, so a crash
// mid-write leaves the previous snapshot intact.
static int save_snapshot(const char *path) {
    std::string tmp = std::string(path) + ".tmp";
    FILE *f = fopen(tmp.c_str(), "w");
    if (!f) return -1;

    fwrite("PRISMDB\n", 1, 8, f);
    uint32_t count = (uint32_t)hm_size(&g_data.db);
    fwrite(&count, 4, 1, f);
    hm_foreach(&g_data.db, &cb_save, (void *)f);

    bool ok = fflush(f) == 0 && fsync(fileno(f)) == 0;
    ok = fclose(f) == 0 && ok;
    if (!ok || rename(tmp.c_str(), path) != 0) {
        remove(tmp.c_str());
        return -1;
    }
    return 0;
}

static bool read_str(FILE *f, std::string &out) {
    uint32_t len = 0;
    if (fread(&len, 4, 1, f) != 1 || len > k_max_msg) return false;
    out.resize(len);
    return fread(&out[0], 1, len, f) == len;
}

static bool load_value(FILE *f, Entry *ent) {
    if (ent->type == T_STR) {
        return read_str(f, ent->str);
    }
    uint32_t n = 0;
    if (fread(&n, 4, 1, f) != 1) return false;
    for (uint32_t i = 0; i < n; i++) {
        std::string a, b;
        if (ent->type == T_ZSET) {
            double score = 0;
            if (fread(&score, 8, 1, f) != 1 || !read_str(f, a)) return false;
            zset_insert(&ent->zset, a.data(), a.size(), score);
        } else if (ent->type == T_LIST) {
            if (!read_str(f, a)) return false;
            llist_push(&ent->list, a);
        } else if (ent->type == T_HASH) {
            if (!read_str(f, a) || !read_str(f, b)) return false;
            HEntry *he = new HEntry();
            he->field.swap(a);
            he->val.swap(b);
            he->node.hcode = str_hash((uint8_t *)he->field.data(), he->field.size());
            hm_insert(&ent->hash_map, &he->node);
        } else {
            return false;
        }
    }
    return true;
}

// Returns 0 on success, -1 if the file is absent or corrupt. On corruption the
// keys read before the damaged record stay loaded.
static int load_snapshot(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;

    uint8_t magic[8];
    uint32_t count = 0;
    if (fread(magic, 1, 8, f) != 8 || memcmp(magic, "PRISMDB\n", 8) != 0
        || fread(&count, 4, 1, f) != 1) {
        fclose(f);
        return -1;
    }

    int rv = 0;
    for (uint32_t i = 0; i < count; i++) {
        Entry *ent = entry_new(T_INIT);
        uint8_t typ = 0;
        uint64_t expire = 0;
        bool ok = read_str(f, ent->key) && fread(&typ, 1, 1, f) == 1
            && fread(&expire, 8, 1, f) == 1;
        ent->type = typ;
        if (!ok || !load_value(f, ent)) {
            entry_del_sync(ent);
            rv = -1;
            break;
        }
        if (expire > 0 && expire <= get_wall_msec()) {
            entry_del_sync(ent);    // expired while the server was down
            continue;
        }
        ent->node.hcode = str_hash((uint8_t *)ent->key.data(), ent->key.size());
        hm_insert(&g_data.db, &ent->node);
        if (expire > 0) {
            entry_set_deadline(ent, wall_to_monotonic(expire));
        }
    }

    fclose(f);
    return rv;
}

static void aof_replay(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return;

    uint8_t header[4];
    Buffer dummy;
    std::vector<std::string> cmd;

    while (fread(header, 1, 4, f) == 4) {
        uint32_t body_len = 0;
        memcpy(&body_len, header, 4);
        if (body_len > k_max_msg) break;

        std::vector<uint8_t> body(body_len);
        if (fread(body.data(), 1, body_len, f) != body_len) break;

        cmd.clear();
        if (parse_req(body.data(), body_len, cmd) == 0 && !cmd.empty()) {
            dummy.clear();
            do_request(cmd, NULL, dummy);
        }
    }
    fclose(f);
    fprintf(stderr, "aof replay done: %s\n", path);
}

static void persistence_init() {
    if (load_snapshot(k_rdb_path) == 0) {
        fprintf(stderr, "loaded snapshot\n");
    }
    aof_replay(k_aof_pre_path);
    aof_replay(k_aof_path);
    aof_open();
    aof_last_sync_ms = get_monotonic_msec();
}

// the log restarts empty once a snapshot covers everything in it
static void aof_reset() {
    if (aof_file) fclose(aof_file);
    remove(k_aof_pre_path);
    aof_file = fopen(k_aof_path, "w");
    aof_dirty = false;
}

// appends the current log to prism.aof.pre and starts an empty log
static int aof_rotate_for_bgsave() {
    if (aof_file) fclose(aof_file);
    aof_file = NULL;
    FILE *src = fopen(k_aof_path, "r");
    FILE *dst = fopen(k_aof_pre_path, "a");
    int rv = src && dst ? 0 : -1;
    char buf[64 * 1024];
    size_t n = 0;
    while (rv == 0 && (n = fread(buf, 1, sizeof(buf), src)) > 0) {
        if (fwrite(buf, 1, n, dst) != n) rv = -1;
    }
    if (dst && (fflush(dst) != 0 || fsync(fileno(dst)) != 0)) rv = -1;
    if (src) fclose(src);
    if (dst) fclose(dst);
    aof_file = fopen(k_aof_path, rv == 0 ? "w" : "a");
    aof_dirty = false;
    return rv;
}

// collects finished bgsave children so they do not linger as zombies
static void reap_children() {
    int status = 0;
    pid_t pid;
    while ((pid = waitpid(-1, &status, WNOHANG)) > 0) {
        if (pid != bgsave_pid) continue;
        bgsave_pid = -1;
        if (WIFEXITED(status) && WEXITSTATUS(status) == 0) {
            remove(k_aof_pre_path);
        } else {
            fprintf(stderr, "bgsave failed, keeping %s\n", k_aof_pre_path);
        }
    }
}

static void do_save(std::vector<std::string> &, Buffer &out) {
    if (bgsave_pid != -1) {
        return out_err(out, ERR_UNKNOWN, "bgsave in progress");
    }
    if (save_snapshot(k_rdb_path) != 0) {
        return out_err(out, ERR_UNKNOWN, "save failed");
    }
    aof_reset();
    out_nil(out);
}

static void do_bgsave(std::vector<std::string> &, Buffer &out) {
    if (bgsave_pid != -1) {
        return out_err(out, ERR_UNKNOWN, "bgsave in progress");
    }
    if (aof_rotate_for_bgsave() != 0) {
        return out_err(out, ERR_UNKNOWN, "cannot rotate the append-only file");
    }
    pid_t pid = fork();
    if (pid < 0) {
        return out_err(out, ERR_UNKNOWN, "fork failed");
    }
    if (pid == 0) {
        _exit(save_snapshot(k_rdb_path) == 0 ? 0 : 1);
    }
    bgsave_pid = pid;
    out_int(out, (int64_t)pid);
}

static void do_request(std::vector<std::string> &cmd, Conn *conn, Buffer &out) {
    if (cmd.empty()) {
        return out_err(out, ERR_UNKNOWN, "empty command.");
    }
    if (conn && conn->subscribed && cmd[0] != "subscribe" && cmd[0] != "unsubscribe") {
        return out_err(out, ERR_UNKNOWN, "only subscribe/unsubscribe allowed in pub/sub mode");
    }

    if (cmd.size() == 2 && cmd[0] == "get") {
        return do_get(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "set") {
        return do_set(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "del") {
        return do_del(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "pexpire") {
        return do_expire(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "pexpireat") {
        return do_expireat(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "pttl") {
        return do_ttl(cmd, out);
    } else if (cmd.size() == 1 && cmd[0] == "keys") {
        return do_keys(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "zadd") {
        return do_zadd(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "zrem") {
        return do_zrem(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "zscore") {
        return do_zscore(cmd, out);
    } else if (cmd.size() == 6 && cmd[0] == "zquery") {
        return do_zquery(cmd, out);
    } else if (cmd.size() >= 2 && cmd[0] == "lpush") {
        return do_lpush(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "lpop") {
        return do_lpop(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "llen") {
        return do_llen(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "lrange") {
        return do_lrange(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "hset") {
        return do_hset(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "hget") {
        return do_hget(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "hdel") {
        return do_hdel(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "hgetall") {
        return do_hgetall(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "setbit") {
        return do_setbit(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "getbit") {
        return do_getbit(cmd, out);
    } else if (cmd.size() >= 2 && cmd.size() <= 4 && cmd[0] == "bitcount") {
        return do_bitcount(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "exists") {
        return do_exists(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "type") {
        return do_type(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "strlen") {
        return do_strlen(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "rename") {
        return do_rename(cmd, out);
    } else if (cmd.size() >= 2 && cmd.size() <= 4 && cmd[0] == "scan") {
        return do_scan(cmd, out);
    } else if (cmd.size() == 1 && cmd[0] == "debug") {
        return do_debug(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "object") {
        return do_object(cmd, out);
    } else if (cmd[0] == "subscribe") {
        // a valid subscribe is answered by try_one_request with one frame per channel
        return out_err(out, ERR_BAD_ARG, "wrong number of arguments for subscribe");
    } else if (cmd.size() == 3 && cmd[0] == "publish") {
        return do_publish(cmd, conn, out);
    } else if (cmd.size() == 1 && cmd[0] == "save") {
        return do_save(cmd, out);
    } else if (cmd.size() == 1 && cmd[0] == "bgsave") {
        return do_bgsave(cmd, out);
    } else {
        return out_err(out, ERR_UNKNOWN, "unknown command.");
    }
}

static void response_begin(Buffer &out, size_t *header) {
    *header = out.size();       // messege header position
    buf_append_u32(out, 0);     // reserve space
}
static size_t response_size(Buffer &out, size_t header) {
    return out.size() - header - 4;
}
static void response_end(Buffer &out, size_t header) {
    size_t msg_size = response_size(out, header);
    if (msg_size > k_max_msg) {
        out.resize(header + 4);
        out_err(out, ERR_TOO_BIG, "response is too big.");
        msg_size = response_size(out, header);
    }
    // message header
    uint32_t len = (uint32_t)msg_size;
    memcpy(&out[header], &len, 4);
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn) {
    // try to parse the protocol: message header
    if (conn->incoming.size() < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if (len > k_max_msg) {
        msg("too long");
        conn->want_close = true;
        return false;   // want close
    }
    // message body
    if (4 + len > conn->incoming.size()) {
        return false;   // want read
    }
    const uint8_t *request = &conn->incoming[4];

    // got one request, do some application logic
    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0) {
        msg("bad request");
        conn->want_close = true;
        return false;   // want close
    }
    if (cmd.size() >= 2 && cmd[0] == "subscribe") {
        do_subscribe(cmd, conn, conn->outgoing);
    } else if (!cmd.empty() && cmd[0] == "unsubscribe") {
        do_unsubscribe(cmd, conn, conn->outgoing);
    } else {
        size_t header_pos = 0;
        response_begin(conn->outgoing, &header_pos);
        do_request(cmd, conn, conn->outgoing);
        response_end(conn->outgoing, header_pos);
    }

    // log write commands to append-only file
    if (!cmd.empty() && is_write_cmd(cmd[0])) {
        aof_log(cmd, conn->incoming.data(), 4 + len);
    }

    // application logic done! remove the request message.
    buf_consume(conn->incoming, 4 + len);
    // Q: Why not just empty the buffer? See the explanation of "pipelining".
    return true;        // success
}

// application callback when the socket is writable
static void handle_write(Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->want_close = true;    // error handling
        return;
    }

    // remove written data from `outgoing`
    buf_consume(conn->outgoing, (size_t)rv);

    // update the readiness intention
    if (conn->outgoing.size() == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

// application callback when the socket is readable
static void handle_read(Conn *conn) {
    // read some data
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0) {
        if (conn->incoming.size() == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }
    // got some new data
    buf_append(conn->incoming, buf, (size_t)rv);

    // parse requests and generate responses
    while (try_one_request(conn)) {}
    // Q: Why calling this in a loop? See the explanation of "pipelining".

    // update the readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(conn);
    }   // else: want read
}

const uint64_t k_idle_timeout_ms = 5 * 1000;

static int32_t next_timer_ms() {
    uint64_t now_ms = get_monotonic_msec();
    uint64_t next_ms = (uint64_t)-1;
    // idle timers using a linked list
    if (!dlist_empty(&g_data.idle_list)) {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        next_ms = conn->last_active_ms + k_idle_timeout_ms;
    }
    // TTL timers using a heap
    if (!g_data.heap.empty() && g_data.heap[0].val < next_ms) {
        next_ms = g_data.heap[0].val;
    }
    // pending fsync, or a bgsave child to reap
    uint64_t poll_ms = bgsave_pid != -1 ? 100 : aof_dirty ? 1000 : (uint64_t)-1;
    if (poll_ms != (uint64_t)-1 && now_ms + poll_ms < next_ms) {
        next_ms = now_ms + poll_ms;
    }
    // timeout value
    if (next_ms == (uint64_t)-1) {
        return -1;  // no timers, no timeouts
    }
    if (next_ms <= now_ms) {
        return 0;   // missed?
    }
    return (int32_t)std::min<uint64_t>(next_ms - now_ms, INT32_MAX);
}

static void process_timers() {
    reap_children();
    aof_sync();
    uint64_t now_ms = get_monotonic_msec();
    // idle timers using a linked list
    while (!dlist_empty(&g_data.idle_list)) {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        uint64_t next_ms = conn->last_active_ms + k_idle_timeout_ms;
        if (next_ms >= now_ms) {
            break;  // not expired
        }

        fprintf(stderr, "removing idle connection: %d\n", conn->fd);
        conn_destroy(conn);
    }
    // TTL timers using a heap
    const size_t k_max_works = 2000;
    size_t nworks = 0;
    const std::vector<HeapItem> &heap = g_data.heap;
    while (!heap.empty() && heap[0].val < now_ms) {
        entry_remove(container_of(heap[0].ref, Entry, heap_idx));
        if (nworks++ >= k_max_works) {
            // don't stall the server if too many keys are expiring at once
            break;
        }
    }
}

int main() {
    // initialization
    dlist_init(&g_data.idle_list);
    thread_pool_init(&g_data.thread_pool, 4);

    persistence_init();

    // the listening socket
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        die("socket()");
    }
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(1234);
    addr.sin_addr.s_addr = ntohl(0);    // wildcard address 0.0.0.0
    int rv = bind(fd, (const sockaddr *)&addr, sizeof(addr));
    if (rv) {
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, SOMAXCONN);
    if (rv) {
        die("listen()");
    }

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true) {
        // prepare the arguments of the poll()
        poll_args.clear();
        // put the listening sockets in the first position
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args.push_back(pfd);
        // the rest are connection sockets
        for (Conn *conn : g_data.fd2conn) {
            if (!conn) {
                continue;
            }
            // always poll() for error
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            // poll() flags from the application's intent
            if (conn->want_read) {
                pfd.events |= POLLIN;
            }
            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness
        int32_t timeout_ms = next_timer_ms();
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), timeout_ms);
        if (rv < 0 && errno == EINTR) {
            continue;   // not an error
        }
        if (rv < 0) {
            die("poll");
        }

        // handle the listening socket
        if (poll_args[0].revents) {
            handle_accept(fd);
        }

        // handle connection sockets
        for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            if (ready == 0) {
                continue;
            }
            // flags and liveness can change mid-iteration: a publish earlier
            // in this loop may have flipped this connection to writing, or
            // destroyed it as a slow subscriber
            Conn *conn = g_data.fd2conn[poll_args[i].fd];
            if (!conn) {
                continue;
            }

            // update the idle timer by moving conn to the end of the list
            conn->last_active_ms = get_monotonic_msec();
            dlist_detach(&conn->idle_node);
            dlist_insert_before(&g_data.idle_list, &conn->idle_node);

            // handle IO
            if ((ready & POLLIN) && conn->want_read) {
                handle_read(conn);  // application logic
            }
            if ((ready & POLLOUT) && conn->want_write) {
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if ((ready & POLLERR) || conn->want_close) {
                conn_destroy(conn);
            }
        }   // for each connection sockets

        // handle timers
        process_timers();
    }   // the event loop
    return 0;
}
