// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <math.h>   // isnan
// system
#include <time.h>
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
// C++
#include <string>
#include <vector>
#include <unordered_map>
#include <algorithm>
// proj
#include "common.h"
#include "hashtable.h"
#include "zset.h"
#include "list.h"
#include "heap.h"
#include "thread_pool.h"
#include "list_type.h"
#include "hash_type.h"


static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

static uint64_t get_monotonic_msec() {
    struct timespec tv = {0, 0};
    clock_gettime(CLOCK_MONOTONIC, &tv);
    return uint64_t(tv.tv_sec) * 1000 + tv.tv_nsec / 1000 / 1000;
}

static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

const size_t k_max_msg = 32 << 20;  // likely larger than the kernel buffer

typedef std::vector<uint8_t> Buffer;

// append to the back
static void buf_append(Buffer &buf, const uint8_t *data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}
// remove from the front
static void buf_consume(Buffer &buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming;    // data to be parsed by the application
    Buffer outgoing;    // responses generated by the application
    // timer
    uint64_t last_active_ms = 0;
    DList idle_node;
    // pub/sub
    bool subscribed = false;
    std::vector<std::string> channels;
};

// global states
static struct {
    HMap db;
    // a map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;
    // timers for idle connections
    DList idle_list;
    // timers for TTLs
    std::vector<HeapItem> heap;
    // the thread pool
    TheadPool thread_pool;
    // pub/sub: channel -> subscribers
    std::unordered_map<std::string, std::vector<Conn *>> subs;
} g_data;

// application callback when the listening socket is ready
static int32_t handle_accept(int fd) {
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0) {
        msg_errno("accept() error");
        return -1;
    }
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
        ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
        ntohs(client_addr.sin_port)
    );

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a `struct Conn`
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    conn->last_active_ms = get_monotonic_msec();
    dlist_insert_before(&g_data.idle_list, &conn->idle_node);

    // put it into the map
    if (g_data.fd2conn.size() <= (size_t)conn->fd) {
        g_data.fd2conn.resize(conn->fd + 1);
    }
    assert(!g_data.fd2conn[conn->fd]);
    g_data.fd2conn[conn->fd] = conn;
    return 0;
}

static void conn_destroy(Conn *conn) {
    // remove from pub/sub channels
    for (const std::string &ch : conn->channels) {
        auto it = g_data.subs.find(ch);
        if (it != g_data.subs.end()) {
            std::vector<Conn *> &vec = it->second;
            vec.erase(std::remove(vec.begin(), vec.end(), conn), vec.end());
            if (vec.empty()) {
                g_data.subs.erase(it);
            }
        }
    }
    conn->channels.clear();
    conn->subscribed = false;

    (void)close(conn->fd);
    g_data.fd2conn[conn->fd] = NULL;
    dlist_detach(&conn->idle_node);
    delete conn;
}

const size_t k_max_args = 200 * 1000;

static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out) {
    if (cur + 4 > end) {
        return false;
    }
    memcpy(&out, cur, 4);
    cur += 4;
    return true;
}

static bool
read_str(const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out) {
    if (cur + n > end) {
        return false;
    }
    out.assign(cur, cur + n);
    cur += n;
    return true;
}

// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+

static int32_t
parse_req(const uint8_t *data, size_t size, std::vector<std::string> &out) {
    const uint8_t *end = data + size;
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr)) {
        return -1;
    }
    if (nstr > k_max_args) {
        return -1;  // safety limit
    }

    while (out.size() < nstr) {
        uint32_t len = 0;
        if (!read_u32(data, end, len)) {
            return -1;
        }
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back())) {
            return -1;
        }
    }
    if (data != end) {
        return -1;  // trailing garbage
    }
    return 0;
}

// error code for TAG_ERR
enum {
    ERR_UNKNOWN = 1,    // unknown command
    ERR_TOO_BIG = 2,    // response too big
    ERR_BAD_TYP = 3,    // unexpected value type
    ERR_BAD_ARG = 4,    // bad arguments
};

// data types of serialized data
enum {
    TAG_NIL = 0,    // nil
    TAG_ERR = 1,    // error code + msg
    TAG_STR = 2,    // string
    TAG_INT = 3,    // int64
    TAG_DBL = 4,    // double
    TAG_ARR = 5,    // array
};

// help functions for the serialization
static void buf_append_u8(Buffer &buf, uint8_t data) {
    buf.push_back(data);
}
static void buf_append_u32(Buffer &buf, uint32_t data) {
    buf_append(buf, (const uint8_t *)&data, 4);
}
static void buf_append_i64(Buffer &buf, int64_t data) {
    buf_append(buf, (const uint8_t *)&data, 8);
}
static void buf_append_dbl(Buffer &buf, double data) {
    buf_append(buf, (const uint8_t *)&data, 8);
}

// append serialized data types to the back
static void out_nil(Buffer &out) {
    buf_append_u8(out, TAG_NIL);
}
static void out_str(Buffer &out, const char *s, size_t size) {
    buf_append_u8(out, TAG_STR);
    buf_append_u32(out, (uint32_t)size);
    buf_append(out, (const uint8_t *)s, size);
}
static void out_int(Buffer &out, int64_t val) {
    buf_append_u8(out, TAG_INT);
    buf_append_i64(out, val);
}
static void out_dbl(Buffer &out, double val) {
    buf_append_u8(out, TAG_DBL);
    buf_append_dbl(out, val);
}
static void out_err(Buffer &out, uint32_t code, const std::string &msg) {
    buf_append_u8(out, TAG_ERR);
    buf_append_u32(out, code);
    buf_append_u32(out, (uint32_t)msg.size());
    buf_append(out, (const uint8_t *)msg.data(), msg.size());
}
static void out_arr(Buffer &out, uint32_t n) {
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, n);
}
static size_t out_begin_arr(Buffer &out) {
    out.push_back(TAG_ARR);
    buf_append_u32(out, 0);     // filled by out_end_arr()
    return out.size() - 4;      // the `ctx` arg
}
static void out_end_arr(Buffer &out, size_t ctx, uint32_t n) {
    assert(out[ctx - 1] == TAG_ARR);
    memcpy(&out[ctx], &n, 4);
}

// value types
enum {
    T_INIT  = 0,
    T_STR   = 1,    // string
    T_ZSET  = 2,    // sorted set
    T_LIST  = 3,    // linked list
    T_HASH  = 4,    // hash map
};

// KV pair for the top-level hashtable
struct Entry {
    struct HNode node;      // hashtable node
    std::string key;
    // for TTL
    size_t heap_idx = -1;   // array index to the heap item
    // value
    uint32_t type = 0;
    // one of the following
    std::string str;
    ZSet zset;
    LList list;
    HMap hash_map;
};

static Entry *entry_new(uint32_t type) {
    Entry *ent = new Entry();
    ent->type = type;
    return ent;
}

static void entry_set_ttl(Entry *ent, int64_t ttl_ms);

static void entry_del_sync(Entry *ent) {
    if (ent->type == T_ZSET) {
        zset_clear(&ent->zset);
    } else if (ent->type == T_LIST) {
        llist_clear(&ent->list);
    } else if (ent->type == T_HASH) {
        hm_clear(&ent->hash_map);
    }
    delete ent;
}

static void entry_del_func(void *arg) {
    entry_del_sync((Entry *)arg);
}

static void entry_del(Entry *ent) {
    // unlink it from any data structures
    entry_set_ttl(ent, -1); // remove from the heap data structure
    // run the destructor in a thread pool for large data structures
    size_t container_size = 0;
    if (ent->type == T_ZSET) {
        container_size = hm_size(&ent->zset.hmap);
    } else if (ent->type == T_LIST) {
        container_size = ent->list.len;
    } else if (ent->type == T_HASH) {
        container_size = hm_size(&ent->hash_map);
    }
    const size_t k_large_container_size = 1000;
    if (container_size > k_large_container_size) {
        thread_pool_queue(&g_data.thread_pool, &entry_del_func, ent);
    } else {
        entry_del_sync(ent);    // small; avoid context switches
    }
}

struct LookupKey {
    struct HNode node;  // hashtable node
    std::string key;
};

// equality comparison for the top-level hashstable
static bool entry_eq(HNode *node, HNode *key) {
    struct Entry *ent = container_of(node, struct Entry, node);
    struct LookupKey *keydata = container_of(key, struct LookupKey, node);
    return ent->key == keydata->key;
}

static void do_get(std::vector<std::string> &cmd, Buffer &out) {
    // a dummy struct just for the lookup
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node) {
        return out_nil(out);
    }
    // copy the value
    Entry *ent = container_of(node, Entry, node);
    if (ent->type != T_STR) {
        return out_err(out, ERR_BAD_TYP, "not a string value");
    }
    return out_str(out, ent->str.data(), ent->str.size());
}

static void do_set(std::vector<std::string> &cmd, Buffer &out) {
    // a dummy struct just for the lookup
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node) {
        // found, update the value
        Entry *ent = container_of(node, Entry, node);
        if (ent->type != T_STR) {
            return out_err(out, ERR_BAD_TYP, "a non-string value exists");
        }
        ent->str.swap(cmd[2]);
    } else {
        // not found, allocate & insert a new pair
        Entry *ent = entry_new(T_STR);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        ent->str.swap(cmd[2]);
        hm_insert(&g_data.db, &ent->node);
    }
    return out_nil(out);
}

static void do_del(std::vector<std::string> &cmd, Buffer &out) {
    // a dummy struct just for the lookup
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable delete
    HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
    if (node) { // deallocate the pair
        entry_del(container_of(node, Entry, node));
    }
    return out_int(out, node ? 1 : 0);
}

static void heap_delete(std::vector<HeapItem> &a, size_t pos) {
    // swap the erased item with the last item
    a[pos] = a.back();
    a.pop_back();
    // update the swapped item
    if (pos < a.size()) {
        heap_update(a.data(), pos, a.size());
    }
}

static void heap_upsert(std::vector<HeapItem> &a, size_t pos, HeapItem t) {
    if (pos < a.size()) {
        a[pos] = t;         // update an existing item
    } else {
        pos = a.size();
        a.push_back(t);     // or add a new item
    }
    heap_update(a.data(), pos, a.size());
}

// set or remove the TTL
static void entry_set_ttl(Entry *ent, int64_t ttl_ms) {
    if (ttl_ms < 0 && ent->heap_idx != (size_t)-1) {
        // setting a negative TTL means removing the TTL
        heap_delete(g_data.heap, ent->heap_idx);
        ent->heap_idx = -1;
    } else if (ttl_ms >= 0) {
        // add or update the heap data structure
        uint64_t expire_at = get_monotonic_msec() + (uint64_t)ttl_ms;
        HeapItem item = {expire_at, &ent->heap_idx};
        heap_upsert(g_data.heap, ent->heap_idx, item);
    }
}

static bool str2int(const std::string &s, int64_t &out) {
    char *endp = NULL;
    out = strtoll(s.c_str(), &endp, 10);
    return endp == s.c_str() + s.size();
}

// PEXPIRE key ttl_ms
static void do_expire(std::vector<std::string> &cmd, Buffer &out) {
    int64_t ttl_ms = 0;
    if (!str2int(cmd[2], ttl_ms)) {
        return out_err(out, ERR_BAD_ARG, "expect int64");
    }

    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node) {
        Entry *ent = container_of(node, Entry, node);
        entry_set_ttl(ent, ttl_ms);
    }
    return out_int(out, node ? 1: 0);
}

// PTTL key
static void do_ttl(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node) {
        return out_int(out, -2);    // not found
    }

    Entry *ent = container_of(node, Entry, node);
    if (ent->heap_idx == (size_t)-1) {
        return out_int(out, -1);    // no TTL
    }

    uint64_t expire_at = g_data.heap[ent->heap_idx].val;
    uint64_t now_ms = get_monotonic_msec();
    return out_int(out, expire_at > now_ms ? (expire_at - now_ms) : 0);
}

static bool cb_keys(HNode *node, void *arg) {
    Buffer &out = *(Buffer *)arg;
    const std::string &key = container_of(node, Entry, node)->key;
    out_str(out, key.data(), key.size());
    return true;
}

static void do_keys(std::vector<std::string> &, Buffer &out) {
    out_arr(out, (uint32_t)hm_size(&g_data.db));
    hm_foreach(&g_data.db, &cb_keys, (void *)&out);
}

static bool str2dbl(const std::string &s, double &out) {
    char *endp = NULL;
    out = strtod(s.c_str(), &endp);
    return endp == s.c_str() + s.size() && !isnan(out);
}

// zadd zset score name
static void do_zadd(std::vector<std::string> &cmd, Buffer &out) {
    double score = 0;
    if (!str2dbl(cmd[2], score)) {
        return out_err(out, ERR_BAD_ARG, "expect float");
    }

    // look up or create the zset
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);

    Entry *ent = NULL;
    if (!hnode) {   // insert a new key
        ent = entry_new(T_ZSET);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        hm_insert(&g_data.db, &ent->node);
    } else {        // check the existing key
        ent = container_of(hnode, Entry, node);
        if (ent->type != T_ZSET) {
            return out_err(out, ERR_BAD_TYP, "expect zset");
        }
    }

    // add or update the tuple
    const std::string &name = cmd[3];
    bool added = zset_insert(&ent->zset, name.data(), name.size(), score);
    return out_int(out, (int64_t)added);
}

static const ZSet k_empty_zset;

static ZSet *expect_zset(std::string &s) {
    LookupKey key;
    key.key.swap(s);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) {   // a non-existent key is treated as an empty zset
        return (ZSet *)&k_empty_zset;
    }
    Entry *ent = container_of(hnode, Entry, node);
    return ent->type == T_ZSET ? &ent->zset : NULL;
}

// zrem zset name
static void do_zrem(std::vector<std::string> &cmd, Buffer &out) {
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset) {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    if (znode) {
        zset_delete(zset, znode);
    }
    return out_int(out, znode ? 1 : 0);
}

// zscore zset name
static void do_zscore(std::vector<std::string> &cmd, Buffer &out) {
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset) {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    return znode ? out_dbl(out, znode->score) : out_nil(out);
}

// zquery zset score name offset limit
static void do_zquery(std::vector<std::string> &cmd, Buffer &out) {
    // parse args
    double score = 0;
    if (!str2dbl(cmd[2], score)) {
        return out_err(out, ERR_BAD_ARG, "expect fp number");
    }
    const std::string &name = cmd[3];
    int64_t offset = 0, limit = 0;
    if (!str2int(cmd[4], offset) || !str2int(cmd[5], limit)) {
        return out_err(out, ERR_BAD_ARG, "expect int");
    }

    // get the zset
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset) {
        return out_err(out, ERR_BAD_TYP, "expect zset");
    }

    // seek to the key
    if (limit <= 0) {
        return out_arr(out, 0);
    }
    ZNode *znode = zset_seekge(zset, score, name.data(), name.size());
    znode = znode_offset(znode, offset);

    // output
    size_t ctx = out_begin_arr(out);
    int64_t n = 0;
    while (znode && n < limit) {
        out_str(out, znode->name, znode->len);
        out_dbl(out, znode->score);
        znode = znode_offset(znode, +1);
        n += 2;
    }
    out_end_arr(out, ctx, (uint32_t)n);
}

// ---- list commands ----

// lpush key val [val ...]
static void do_lpush(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    Entry *ent = NULL;
    if (!hnode) {
        ent = entry_new(T_LIST);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        hm_insert(&g_data.db, &ent->node);
    } else {
        ent = container_of(hnode, Entry, node);
        if (ent->type != T_LIST) {
            return out_err(out, ERR_BAD_TYP, "not a list");
        }
    }
    for (size_t i = 2; i < cmd.size(); i++) {
        llist_push(&ent->list, cmd[i]);
    }
    out_int(out, (int64_t)ent->list.len);
}

// lpop key
static void do_lpop(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_nil(out);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_LIST) return out_err(out, ERR_BAD_TYP, "not a list");

    std::string val;
    if (llist_pop(&ent->list, val)) {
        out_str(out, val.data(), val.size());
    } else {
        out_nil(out);
    }
}

// llen key
static void do_llen(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_int(out, 0);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_LIST) return out_err(out, ERR_BAD_TYP, "not a list");
    out_int(out, (int64_t)ent->list.len);
}

// lrange key start stop
static void do_lrange(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_arr(out, 0);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_LIST) return out_err(out, ERR_BAD_TYP, "not a list");

    int64_t start = 0, stop = 0;
    if (!str2int(cmd[2], start) || !str2int(cmd[3], stop)) {
        return out_err(out, ERR_BAD_ARG, "expect int");
    }

    // convert negative indices
    if (start < 0) start = (int64_t)ent->list.len + start;
    if (stop < 0) stop = (int64_t)ent->list.len + stop;
    if (start < 0) start = 0;
    if (stop < 0 || (size_t)start >= ent->list.len) return out_arr(out, 0);
    if ((size_t)stop >= ent->list.len) stop = (int64_t)ent->list.len - 1;

    size_t n = (size_t)(stop - start + 1);
    out_arr(out, (uint32_t)n);
    LNode *cur = llist_index(&ent->list, start);
    for (size_t i = 0; cur && i < n; i++) {
        out_str(out, cur->val.data(), cur->val.size());
        cur = cur->next;
    }
}

// ---- hash commands ----

// hset key field val
static void do_hset(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    Entry *ent = NULL;
    if (!hnode) {
        ent = entry_new(T_HASH);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        hm_insert(&g_data.db, &ent->node);
    } else {
        ent = container_of(hnode, Entry, node);
        if (ent->type != T_HASH) return out_err(out, ERR_BAD_TYP, "not a hash");
    }

    // lookup field
    HLookup hkey;
    hkey.field = cmd[2];
    hkey.node.hcode = str_hash((uint8_t *)hkey.field.data(), hkey.field.size());
    HNode *fnode = hm_lookup(&ent->hash_map, &hkey.node, &hentry_eq);
    if (fnode) {
        HEntry *he = container_of(fnode, HEntry, node);
        he->val = cmd[3];
        out_int(out, 0);
    } else {
        HEntry *he = new HEntry();
        he->field = cmd[2];
        he->val = cmd[3];
        he->node.hcode = hkey.node.hcode;
        hm_insert(&ent->hash_map, &he->node);
        out_int(out, 1);
    }
}

// hget key field
static void do_hget(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_nil(out);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_HASH) return out_err(out, ERR_BAD_TYP, "not a hash");

    HLookup hkey;
    hkey.field = cmd[2];
    hkey.node.hcode = str_hash((uint8_t *)hkey.field.data(), hkey.field.size());
    HNode *fnode = hm_lookup(&ent->hash_map, &hkey.node, &hentry_eq);
    if (!fnode) return out_nil(out);
    HEntry *he = container_of(fnode, HEntry, node);
    out_str(out, he->val.data(), he->val.size());
}

// hdel key field
static void do_hdel(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_int(out, 0);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_HASH) return out_err(out, ERR_BAD_TYP, "not a hash");

    HLookup hkey;
    hkey.field = cmd[2];
    hkey.node.hcode = str_hash((uint8_t *)hkey.field.data(), hkey.field.size());
    HNode *fnode = hm_delete(&ent->hash_map, &hkey.node, &hentry_eq);
    if (!fnode) return out_int(out, 0);
    HEntry *he = container_of(fnode, HEntry, node);
    delete he;
    out_int(out, 1);
}

// hgetall key
static void do_hgetall(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_arr(out, 0);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_HASH) return out_err(out, ERR_BAD_TYP, "not a hash");

    struct HGetAllCtx { Buffer *out; };
    HGetAllCtx ctx = { &out };
    out_arr(out, (uint32_t)(hm_size(&ent->hash_map) * 2));
    hm_foreach(&ent->hash_map, [](HNode *node, void *arg) -> bool {
        HEntry *he = container_of(node, HEntry, node);
        Buffer *obuf = ((HGetAllCtx *)arg)->out;
        out_str(*obuf, he->field.data(), he->field.size());
        out_str(*obuf, he->val.data(), he->val.size());
        return true;
    }, &ctx);
}

// ---- bitmap commands ----

// setbit key offset value
static void do_setbit(std::vector<std::string> &cmd, Buffer &out) {
    int64_t offset = 0, bit = 0;
    if (!str2int(cmd[2], offset) || !str2int(cmd[3], bit) || offset < 0 || (bit != 0 && bit != 1)) {
        return out_err(out, ERR_BAD_ARG, "expect uint offset and 0/1");
    }

    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    Entry *ent = NULL;
    if (!hnode) {
        ent = entry_new(T_STR);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        hm_insert(&g_data.db, &ent->node);
    } else {
        ent = container_of(hnode, Entry, node);
        if (ent->type != T_STR) return out_err(out, ERR_BAD_TYP, "not a string");
    }

    size_t byte_pos = (size_t)(offset / 8);
    int bit_off = (int)(offset % 8);
    if (byte_pos >= ent->str.size()) {
        ent->str.resize(byte_pos + 1, 0);
    }
    uint8_t old_bit = (ent->str[byte_pos] >> bit_off) & 1;
    if (bit) {
        ent->str[byte_pos] |= (uint8_t)(1 << bit_off);
    } else {
        ent->str[byte_pos] &= (uint8_t)~(1 << bit_off);
    }
    out_int(out, (int64_t)old_bit);
}

// getbit key offset
static void do_getbit(std::vector<std::string> &cmd, Buffer &out) {
    int64_t offset = 0;
    if (!str2int(cmd[2], offset) || offset < 0) {
        return out_err(out, ERR_BAD_ARG, "expect uint offset");
    }

    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_int(out, 0);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_STR) return out_err(out, ERR_BAD_TYP, "not a string");

    size_t byte_pos = (size_t)(offset / 8);
    int bit_off = (int)(offset % 8);
    if (byte_pos >= ent->str.size()) return out_int(out, 0);
    int64_t b = (ent->str[byte_pos] >> bit_off) & 1;
    out_int(out, b);
}

// bitcount key [start end]
static void do_bitcount(std::vector<std::string> &cmd, Buffer &out) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) return out_int(out, 0);
    Entry *ent = container_of(hnode, Entry, node);
    if (ent->type != T_STR) return out_err(out, ERR_BAD_TYP, "not a string");

    size_t start = 0;
    size_t end = ent->str.size();
    if (cmd.size() >= 3) {
        int64_t s = 0;
        if (!str2int(cmd[2], s)) return out_err(out, ERR_BAD_ARG, "expect int");
        if (s < 0) s = (int64_t)ent->str.size() + s;
        if (s < 0) s = 0;
        start = (size_t)s;
    }
    if (cmd.size() >= 4) {
        int64_t e = 0;
        if (!str2int(cmd[3], e)) return out_err(out, ERR_BAD_ARG, "expect int");
        if (e < 0) e = (int64_t)ent->str.size() + e;
        if (e < 0) { out_int(out, 0); return; }
        end = (size_t)e + 1;
    }

    if (start > ent->str.size()) start = ent->str.size();
    if (end > ent->str.size()) end = ent->str.size();

    int64_t count = 0;
    for (size_t i = start; i < end; i++) {
        uint8_t b = ent->str[i];
        // popcount
        while (b) { count += b & 1; b >>= 1; }
    }
    out_int(out, count);
}

static void response_begin(Buffer &out, size_t *header);
static void response_end(Buffer &out, size_t header);
static void do_request(std::vector<std::string> &cmd, Conn *conn, Buffer &out);
static bool hnode_same(HNode *node, HNode *key);

// subscribe channel [channel ...]
static void do_subscribe(std::vector<std::string> &cmd, Conn *conn, Buffer &out) {
    for (size_t i = 1; i < cmd.size(); i++) {
        const std::string &channel = cmd[i];
        auto it = std::find(conn->channels.begin(), conn->channels.end(), channel);
        if (it == conn->channels.end()) {
            conn->channels.push_back(channel);
            g_data.subs[channel].push_back(conn);
        }
        out_arr(out, 3);
        out_str(out, "subscribe", 9);
        out_str(out, channel.data(), channel.size());
        out_int(out, (int64_t)conn->channels.size());
    }
    conn->subscribed = true;
}

// unsubscribe [channel ...]
static void do_unsubscribe(std::vector<std::string> &cmd, Conn *conn, Buffer &out) {
    if (cmd.size() == 1) {
        // unsubscribe all
        std::vector<std::string> all = conn->channels;
        for (size_t i = 0; i < all.size(); i++) {
            auto it = g_data.subs.find(all[i]);
            if (it != g_data.subs.end()) {
                std::vector<Conn *> &vec = it->second;
                vec.erase(std::remove(vec.begin(), vec.end(), conn), vec.end());
                if (vec.empty()) {
                    g_data.subs.erase(it);
                }
            }
            out_arr(out, 3);
            out_str(out, "unsubscribe", 11);
            out_str(out, all[i].data(), all[i].size());
            out_int(out, (int64_t)(all.size() - 1 - i));
        }
        conn->channels.clear();
        conn->subscribed = false;
    } else {
        for (size_t i = 1; i < cmd.size(); i++) {
            const std::string &channel = cmd[i];
            auto it = std::find(conn->channels.begin(), conn->channels.end(), channel);
            if (it != conn->channels.end()) {
                conn->channels.erase(it);
                auto sit = g_data.subs.find(channel);
                if (sit != g_data.subs.end()) {
                    std::vector<Conn *> &vec = sit->second;
                    vec.erase(std::remove(vec.begin(), vec.end(), conn), vec.end());
                    if (vec.empty()) {
                        g_data.subs.erase(sit);
                    }
                }
            }
            out_arr(out, 3);
            out_str(out, "unsubscribe", 11);
            out_str(out, channel.data(), channel.size());
            out_int(out, (int64_t)conn->channels.size());
        }
        if (conn->channels.empty()) {
            conn->subscribed = false;
        }
    }
}

// publish channel message
static void do_publish(std::vector<std::string> &cmd, Conn *conn, Buffer &out) {
    const std::string &channel = cmd[1];
    const std::string &msg = cmd[2];

    auto it = g_data.subs.find(channel);
    int64_t count = 0;
    if (it != g_data.subs.end()) {
        // build the message notification frame
        Buffer notification;
        size_t header;
        response_begin(notification, &header);
        out_arr(notification, 3);
        out_str(notification, "message", 7);
        out_str(notification, channel.data(), channel.size());
        out_str(notification, msg.data(), msg.size());
        response_end(notification, header);

        for (Conn *sub : it->second) {
            buf_append(sub->outgoing, notification.data(), notification.size());
            sub->want_read = false;
            sub->want_write = true;
        }
        count = (int64_t)it->second.size();
    }

    out_int(out, count);
}

// ---- persistence ----

static FILE *aof_file = NULL;

static void aof_init() {
    aof_file = fopen("prism.aof", "a");
    if (!aof_file) {
        fprintf(stderr, "warn: no prism.aof, persistence off\n");
    }
}

static void aof_append(const uint8_t *data, size_t len) {
    if (!aof_file) return;
    fwrite(data, 1, len, aof_file);
    fflush(aof_file);
}

static bool is_write_cmd(const std::string &c) {
    return c == "set" || c == "del" || c == "pexpire" || c == "zadd" || c == "zrem"
        || c == "lpush" || c == "hset" || c == "hdel" || c == "setbit";
}

static bool cb_save(HNode *node, void *arg) {
    FILE *f = (FILE *)arg;
    Entry *ent = container_of(node, Entry, node);

    uint32_t klen = (uint32_t)ent->key.size();
    fwrite(&klen, 4, 1, f);
    fwrite(ent->key.data(), 1, klen, f);

    uint8_t typ = (uint8_t)ent->type;
    fwrite(&typ, 1, 1, f);

    uint64_t expire = 0;
    if (ent->heap_idx != (size_t)-1) {
        expire = g_data.heap[ent->heap_idx].val;
    }
    fwrite(&expire, 8, 1, f);

    if (ent->type == T_STR) {
        uint32_t vlen = (uint32_t)ent->str.size();
        fwrite(&vlen, 4, 1, f);
        fwrite(ent->str.data(), 1, vlen, f);
    } else if (ent->type == T_ZSET) {
        uint32_t n = (uint32_t)hm_size(&ent->zset.hmap);
        fwrite(&n, 4, 1, f);
        struct ZsaveCtx { FILE *f; };
        ZsaveCtx zctx = { f };
        hm_foreach(&ent->zset.hmap, [](HNode *znode, void *arg) -> bool {
            ZNode *z = container_of(znode, ZNode, hmap);
            FILE *fp = ((ZsaveCtx *)arg)->f;
            double score = z->score;
            uint32_t nlen = (uint32_t)z->len;
            fwrite(&score, 8, 1, fp);
            fwrite(&nlen, 4, 1, fp);
            fwrite(z->name, 1, nlen, fp);
            return true;
        }, &zctx);
    } else if (ent->type == T_LIST) {
        uint32_t n = (uint32_t)ent->list.len;
        fwrite(&n, 4, 1, f);
        LNode *cur = ent->list.head;
        while (cur) {
            uint32_t vlen = (uint32_t)cur->val.size();
            fwrite(&vlen, 4, 1, f);
            fwrite(cur->val.data(), 1, vlen, f);
            cur = cur->next;
        }
    } else if (ent->type == T_HASH) {
        uint32_t n = (uint32_t)hm_size(&ent->hash_map);
        fwrite(&n, 4, 1, f);
        struct HsaveCtx { FILE *f; };
        HsaveCtx hctx = { f };
        hm_foreach(&ent->hash_map, [](HNode *hnode, void *arg) -> bool {
            HEntry *he = container_of(hnode, HEntry, node);
            FILE *fp = ((HsaveCtx *)arg)->f;
            uint32_t flen = (uint32_t)he->field.size();
            uint32_t vlen = (uint32_t)he->val.size();
            fwrite(&flen, 4, 1, fp);
            fwrite(he->field.data(), 1, flen, fp);
            fwrite(&vlen, 4, 1, fp);
            fwrite(he->val.data(), 1, vlen, fp);
            return true;
        }, &hctx);
    }
    return true;
}

static int save_snapshot(const char *path) {
    FILE *f = fopen(path, "w");
    if (!f) return -1;

    uint64_t magic = 0x44424d535052494dULL; // "PRISMDB\n" reversed
    // Actually just write the string
    fprintf(f, "PRISMDB\n");

    uint32_t count = (uint32_t)hm_size(&g_data.db);
    fwrite(&count, 4, 1, f);

    hm_foreach(&g_data.db, &cb_save, (void *)f);

    fclose(f);
    return 0;
}

static int load_snapshot(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;

    // check magic
    uint8_t magic[8];
    if (fread(magic, 1, 8, f) != 8 || memcmp(magic, "PRISMDB\n", 8) != 0) {
        fclose(f);
        return -1;
    }

    uint32_t count = 0;
    if (fread(&count, 4, 1, f) != 1) { fclose(f); return -1; }

    for (uint32_t i = 0; i < count; i++) {
        uint32_t klen = 0;
        if (fread(&klen, 4, 1, f) != 1) break;
        std::string key((size_t)klen, '\0');
        if (fread(&key[0], 1, klen, f) != klen) break;

        uint8_t typ = 0;
        if (fread(&typ, 1, 1, f) != 1) break;

        uint64_t expire = 0;
        if (fread(&expire, 8, 1, f) != 1) break;

        Entry *ent = entry_new(typ);
        ent->key = key;
        ent->node.hcode = str_hash((uint8_t *)key.data(), key.size());

        if (typ == T_STR) {
            uint32_t vlen = 0;
            if (fread(&vlen, 4, 1, f) != 1) break;
            ent->str.resize(vlen);
            if (fread(&ent->str[0], 1, vlen, f) != vlen) break;
        } else if (typ == T_ZSET) {
            uint32_t n = 0;
            if (fread(&n, 4, 1, f) != 1) break;
            for (uint32_t j = 0; j < n; j++) {
                double score = 0;
                if (fread(&score, 8, 1, f) != 1) break;
                uint32_t nlen = 0;
                if (fread(&nlen, 4, 1, f) != 1) break;
                std::string name((size_t)nlen, '\0');
                if (fread(&name[0], 1, nlen, f) != nlen) break;
                zset_insert(&ent->zset, name.data(), name.size(), score);
            }
        } else if (typ == T_LIST) {
            uint32_t n = 0;
            if (fread(&n, 4, 1, f) != 1) break;
            for (uint32_t j = 0; j < n; j++) {
                uint32_t vlen = 0;
                if (fread(&vlen, 4, 1, f) != 1) break;
                std::string s((size_t)vlen, '\0');
                if (fread(&s[0], 1, vlen, f) != vlen) break;
                llist_push(&ent->list, s);
            }
        } else if (typ == T_HASH) {
            uint32_t n = 0;
            if (fread(&n, 4, 1, f) != 1) break;
            for (uint32_t j = 0; j < n; j++) {
                uint32_t flen = 0, vlen = 0;
                if (fread(&flen, 4, 1, f) != 1) break;
                std::string field((size_t)flen, '\0');
                if (fread(&field[0], 1, flen, f) != flen) break;
                if (fread(&vlen, 4, 1, f) != 1) break;
                std::string val((size_t)vlen, '\0');
                if (fread(&val[0], 1, vlen, f) != vlen) break;
                HEntry *he = new HEntry();
                he->field = field;
                he->val = val;
                he->node.hcode = str_hash((uint8_t *)field.data(), field.size());
                hm_insert(&ent->hash_map, &he->node);
            }
        }

        hm_insert(&g_data.db, &ent->node);

        // restore TTL
        if (expire > 0) {
            uint64_t now = get_monotonic_msec();
            if (expire > now) {
                ent->heap_idx = g_data.heap.size();
                HeapItem item = {expire, &ent->heap_idx};
                g_data.heap.push_back(item);
                heap_update(g_data.heap.data(), ent->heap_idx, g_data.heap.size());
            } else {
                // already expired, skip it? or delete it now
                HNode *n = hm_delete(&g_data.db, &ent->node, &hnode_same);
                if (n) entry_del(ent);
            }
        }
    }

    fclose(f);
    return 0;
}

static void aof_replay() {
    FILE *f = fopen("prism.aof", "r");
    if (!f) return;

    uint8_t header[4];
    Buffer dummy;
    std::vector<std::string> cmd;

    while (fread(header, 1, 4, f) == 4) {
        uint32_t body_len = 0;
        memcpy(&body_len, header, 4);
        if (body_len > k_max_msg) break;

        uint8_t *body = (uint8_t *)malloc(body_len);
        if (!body) break;
        if (fread(body, 1, body_len, f) != body_len) {
            free(body);
            break;
        }

        cmd.clear();
        if (parse_req(body, body_len, cmd) == 0 && !cmd.empty()) {
            do_request(cmd, NULL, dummy);
        }
        free(body);
    }
    fclose(f);
    fprintf(stderr, "aof replay done\n");
}

static void do_save(std::vector<std::string> &, Buffer &out) {
    if (save_snapshot("prism.rdb") == 0) {
        out_nil(out);
    } else {
        out_err(out, ERR_UNKNOWN, "save failed");
    }
}

static void do_bgsave(std::vector<std::string> &, Buffer &out) {
    pid_t pid = fork();
    if (pid == 0) {
        // child: save and exit
        save_snapshot("prism.rdb");
        _exit(0);
    }
    out_int(out, (int64_t)pid);
}

static void do_request(std::vector<std::string> &cmd, Conn *conn, Buffer &out) {
    if (conn && conn->subscribed && cmd[0] != "subscribe" && cmd[0] != "unsubscribe") {
        return out_err(out, ERR_UNKNOWN, "only subscribe/unsubscribe allowed in pub/sub mode");
    }

    if (cmd.size() == 2 && cmd[0] == "get") {
        return do_get(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "set") {
        return do_set(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "del") {
        return do_del(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "pexpire") {
        return do_expire(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "pttl") {
        return do_ttl(cmd, out);
    } else if (cmd.size() == 1 && cmd[0] == "keys") {
        return do_keys(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "zadd") {
        return do_zadd(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "zrem") {
        return do_zrem(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "zscore") {
        return do_zscore(cmd, out);
    } else if (cmd.size() == 6 && cmd[0] == "zquery") {
        return do_zquery(cmd, out);
    } else if (cmd.size() >= 2 && cmd[0] == "lpush") {
        return do_lpush(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "lpop") {
        return do_lpop(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "llen") {
        return do_llen(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "lrange") {
        return do_lrange(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "hset") {
        return do_hset(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "hget") {
        return do_hget(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "hdel") {
        return do_hdel(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "hgetall") {
        return do_hgetall(cmd, out);
    } else if (cmd.size() == 4 && cmd[0] == "setbit") {
        return do_setbit(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "getbit") {
        return do_getbit(cmd, out);
    } else if (cmd.size() >= 2 && cmd.size() <= 4 && cmd[0] == "bitcount") {
        return do_bitcount(cmd, out);
    } else if (cmd[0] == "subscribe") {
        if (cmd.size() < 2) {
            return out_err(out, ERR_BAD_ARG, "wrong number of arguments for subscribe");
        }
        return do_subscribe(cmd, conn, out);
    } else if (cmd[0] == "unsubscribe") {
        return do_unsubscribe(cmd, conn, out);
    } else if (cmd.size() == 3 && cmd[0] == "publish") {
        return do_publish(cmd, conn, out);
    } else if (cmd.size() == 1 && cmd[0] == "save") {
        return do_save(cmd, out);
    } else if (cmd.size() == 1 && cmd[0] == "bgsave") {
        return do_bgsave(cmd, out);
    } else {
        return out_err(out, ERR_UNKNOWN, "unknown command.");
    }
}

static void response_begin(Buffer &out, size_t *header) {
    *header = out.size();       // messege header position
    buf_append_u32(out, 0);     // reserve space
}
static size_t response_size(Buffer &out, size_t header) {
    return out.size() - header - 4;
}
static void response_end(Buffer &out, size_t header) {
    size_t msg_size = response_size(out, header);
    if (msg_size > k_max_msg) {
        out.resize(header + 4);
        out_err(out, ERR_TOO_BIG, "response is too big.");
        msg_size = response_size(out, header);
    }
    // message header
    uint32_t len = (uint32_t)msg_size;
    memcpy(&out[header], &len, 4);
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn) {
    // try to parse the protocol: message header
    if (conn->incoming.size() < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if (len > k_max_msg) {
        msg("too long");
        conn->want_close = true;
        return false;   // want close
    }
    // message body
    if (4 + len > conn->incoming.size()) {
        return false;   // want read
    }
    const uint8_t *request = &conn->incoming[4];

    // got one request, do some application logic
    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0) {
        msg("bad request");
        conn->want_close = true;
        return false;   // want close
    }
    size_t header_pos = 0;
    response_begin(conn->outgoing, &header_pos);
    do_request(cmd, conn, conn->outgoing);
    response_end(conn->outgoing, header_pos);

    // log write commands to append-only file
    if (is_write_cmd(cmd[0])) {
        aof_append(conn->incoming.data(), 4 + len);
    }

    // application logic done! remove the request message.
    buf_consume(conn->incoming, 4 + len);
    // Q: Why not just empty the buffer? See the explanation of "pipelining".
    return true;        // success
}

// application callback when the socket is writable
static void handle_write(Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->want_close = true;    // error handling
        return;
    }

    // remove written data from `outgoing`
    buf_consume(conn->outgoing, (size_t)rv);

    // update the readiness intention
    if (conn->outgoing.size() == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

// application callback when the socket is readable
static void handle_read(Conn *conn) {
    // read some data
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0) {
        if (conn->incoming.size() == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }
    // got some new data
    buf_append(conn->incoming, buf, (size_t)rv);

    // parse requests and generate responses
    while (try_one_request(conn)) {}
    // Q: Why calling this in a loop? See the explanation of "pipelining".

    // update the readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(conn);
    }   // else: want read
}

const uint64_t k_idle_timeout_ms = 5 * 1000;

static uint32_t next_timer_ms() {
    uint64_t now_ms = get_monotonic_msec();
    uint64_t next_ms = (uint64_t)-1;
    // idle timers using a linked list
    if (!dlist_empty(&g_data.idle_list)) {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        next_ms = conn->last_active_ms + k_idle_timeout_ms;
    }
    // TTL timers using a heap
    if (!g_data.heap.empty() && g_data.heap[0].val < next_ms) {
        next_ms = g_data.heap[0].val;
    }
    // timeout value
    if (next_ms == (uint64_t)-1) {
        return -1;  // no timers, no timeouts
    }
    if (next_ms <= now_ms) {
        return 0;   // missed?
    }
    return (int32_t)(next_ms - now_ms);
}

static bool hnode_same(HNode *node, HNode *key) {
    return node == key;
}

static void process_timers() {
    uint64_t now_ms = get_monotonic_msec();
    // idle timers using a linked list
    while (!dlist_empty(&g_data.idle_list)) {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        uint64_t next_ms = conn->last_active_ms + k_idle_timeout_ms;
        if (next_ms >= now_ms) {
            break;  // not expired
        }

        fprintf(stderr, "removing idle connection: %d\n", conn->fd);
        conn_destroy(conn);
    }
    // TTL timers using a heap
    const size_t k_max_works = 2000;
    size_t nworks = 0;
    const std::vector<HeapItem> &heap = g_data.heap;
    while (!heap.empty() && heap[0].val < now_ms) {
        Entry *ent = container_of(heap[0].ref, Entry, heap_idx);
        HNode *node = hm_delete(&g_data.db, &ent->node, &hnode_same);
        assert(node == &ent->node);
        // fprintf(stderr, "key expired: %s\n", ent->key.c_str());
        // delete the key
        entry_del(ent);
        if (nworks++ >= k_max_works) {
            // don't stall the server if too many keys are expiring at once
            break;
        }
    }
}

int main() {
    // initialization
    dlist_init(&g_data.idle_list);
    thread_pool_init(&g_data.thread_pool, 4);

    // load data from disk
    if (load_snapshot("prism.rdb") == 0) {
        fprintf(stderr, "loaded snapshot\n");
    }
    aof_init();
    aof_replay();

    // the listening socket
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        die("socket()");
    }
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(1234);
    addr.sin_addr.s_addr = ntohl(0);    // wildcard address 0.0.0.0
    int rv = bind(fd, (const sockaddr *)&addr, sizeof(addr));
    if (rv) {
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, SOMAXCONN);
    if (rv) {
        die("listen()");
    }

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true) {
        // prepare the arguments of the poll()
        poll_args.clear();
        // put the listening sockets in the first position
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args.push_back(pfd);
        // the rest are connection sockets
        for (Conn *conn : g_data.fd2conn) {
            if (!conn) {
                continue;
            }
            // always poll() for error
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            // poll() flags from the application's intent
            if (conn->want_read) {
                pfd.events |= POLLIN;
            }
            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness
        int32_t timeout_ms = next_timer_ms();
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), timeout_ms);
        if (rv < 0 && errno == EINTR) {
            continue;   // not an error
        }
        if (rv < 0) {
            die("poll");
        }

        // handle the listening socket
        if (poll_args[0].revents) {
            handle_accept(fd);
        }

        // handle connection sockets
        for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            if (ready == 0) {
                continue;
            }
            Conn *conn = g_data.fd2conn[poll_args[i].fd];

            // update the idle timer by moving conn to the end of the list
            conn->last_active_ms = get_monotonic_msec();
            dlist_detach(&conn->idle_node);
            dlist_insert_before(&g_data.idle_list, &conn->idle_node);

            // handle IO
            if (ready & POLLIN) {
                assert(conn->want_read);
                handle_read(conn);  // application logic
            }
            if (ready & POLLOUT) {
                assert(conn->want_write);
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if ((ready & POLLERR) || conn->want_close) {
                conn_destroy(conn);
            }
        }   // for each connection sockets

        // handle timers
        process_timers();
    }   // the event loop
    return 0;
}
